FROM node:21.1.0

# set docker working directory to /app/backend
WORKDIR /app/backend

# copy content of backend directory into docker working directory
COPY ./backend .

# Install dependencies.
RUN npm install 

# The default command to run when starting the container
CMD ["npm", "run", "start"]
