FROM node:21.1.0

# set docker working directory to mkdir /app/frontend
WORKDIR /app/frontend

# Copy package.json and package-lock.json
COPY ./frontend/package*.json .

# Install dependencies.
RUN npm install

# Copy the rest of the frontend directory into the container
COPY ./frontend .

# Build the Next.js app.
RUN npm run build

# The default command to run when starting the container
CMD ["npm", "run", "preview"]
